export const profiles = [
  {
    id: 1,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 2,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
    imageUrl:
      'https://lh5.googleusercontent.com/-frwCJuH1tS8/AAAAAAAAAAI/AAAAAAAAABU/XkOcKICgado/s96-c/photo.jpg',
  },
  {
    id: 3,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 4,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
  },
  {
    id: 5,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 6,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
  },
  {
    id: 7,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 8,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
  },
  {
    id: 9,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 10,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
  },
  {
    id: 11,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 12,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
  },
  {
    id: 13,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 14,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
  },
  {
    id: 15,
    firstName: 'Eun Soo',
    lastName: 'Jung',
    email: 'eunsoojung@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JAVA', 'Spring'],
    degree: 'Master of Science',
  },
  {
    id: 16,
    firstName: 'Mason',
    lastName: 'Shin',
    email: 'masonshin@email.com',
    jobTitle: 'Software Engineer',
    skills: ['JavaScript', 'HTML'],
    degree: 'Master of Science',
  },
];
